export const FULL_CONVERSION_DEBOUNCE_MS = 200;
export const MUTATION_SUPPRESSION_RELEASE_MS = 400;

export const PARTIAL_CONVERSION_DEBOUNCE_MS = 120;
export const PARTIAL_CONVERSION_CONTINUE_MS = 28;
export const PARTIAL_CONVERSION_TIME_BUDGET_MS = 16;
export const PARTIAL_CONVERSION_MAX_NODES_PER_PASS = 4000;
