#!/usr/bin/env node

import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
const START_MARKER = "<!-- AUTO-GENERATED:START -->";
const END_MARKER = "<!-- AUTO-GENERATED:END -->";
const CHECK_MODE = process.argv.includes("--check");

const repoRoot = process.cwd();
const readmePath = path.join(repoRoot, "README.md");
const wxtConfigPath = path.join(repoRoot, "wxt.config.ts");
const ratesPath = path.join(repoRoot, "apps/extension/utils/rates/providers.ts");
const testsRoot = path.join(repoRoot, "apps/extension/tests");
const releaseTestsRoot = path.join(repoRoot, "test");
const packageJsonPath = path.join(repoRoot, "package.json");

function readFileSafe(filePath) {
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch {
    return "";
  }
}

function fileExists(relativePath) {
  return fs.existsSync(path.join(repoRoot, relativePath));
}

function runGitCommand(command) {
  try {
    return execSync(command, {
      cwd: repoRoot,
      stdio: ["ignore", "pipe", "ignore"],
      encoding: "utf8",
    }).trim();
  } catch {
    return "";
  }
}

function extractStringArrayByKey(source, key) {
  const keyPattern = `${key}:\\s*\\[([\\s\\S]*?)\\]`;
  const match = source.match(new RegExp(keyPattern, "m"));
  if (!match?.[1]) {
    return [];
  }

  return Array.from(match[1].matchAll(/"([^"]+)"/g), (entry) => entry[1]);
}

function extractRateProviderUrls(source) {
  return Array.from(source.matchAll(/url:\s*"([^"]+)"/g), (entry) => entry[1]);
}

function walkTestFiles(directoryPath) {
  if (!fs.existsSync(directoryPath)) {
    return [];
  }

  const files = [];
  const entries = fs.readdirSync(directoryPath, { withFileTypes: true });

  for (const entry of entries) {
    const absolutePath = path.join(directoryPath, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkTestFiles(absolutePath));
      continue;
    }

    if (entry.isFile() && entry.name.endsWith(".test.mjs")) {
      files.push(absolutePath);
    }
  }

  return files;
}

function countTestsBySuite(testFiles) {
  const counts = new Map();

  for (const filePath of testFiles) {
    let suiteKey = "other";

    if (filePath.startsWith(`${testsRoot}${path.sep}`)) {
      const relativePath = path.relative(testsRoot, filePath);
      const [suiteName] = relativePath.split(path.sep);
      suiteKey = suiteName || suiteKey;
    } else if (filePath.startsWith(`${releaseTestsRoot}${path.sep}`)) {
      const relativePath = path.relative(releaseTestsRoot, filePath);
      const [suiteName] = relativePath.split(path.sep);
      suiteKey = suiteName || suiteKey;
    }

    counts.set(suiteKey, (counts.get(suiteKey) ?? 0) + 1);
  }

  return Array.from(counts.entries()).sort(([a], [b]) => a.localeCompare(b));
}

function escapeTableText(value) {
  return String(value).replace(/\|/g, "\\|");
}

function getRecentCommits(limit = 8) {
  const sampleSize = Math.max(limit * 5, 25);
  const excludedCommitHashes = new Set(["c821362"]);
  const raw = runGitCommand(
    `git log --first-parent --date=short --pretty=format:%h%x1f%ad%x1f%s -n ${sampleSize}`,
  );
  if (!raw) {
    return [];
  }

  return raw
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      const [hash, date, subject] = line.split("\x1f");
      return { hash, date, subject };
    })
    .filter((commit) => {
      const normalizedSubject = commit.subject.toLowerCase();
      return !(
        excludedCommitHashes.has(commit.hash) ||
        normalizedSubject.includes("docs: sync readme snapshot") ||
        normalizedSubject.includes("readme sync") ||
        normalizedSubject.includes("chore/readme-sync")
      );
    })
    .slice(0, limit);
}

function buildAutoSection() {
  const packageJson = JSON.parse(readFileSafe(packageJsonPath));
  const wxtConfigSource = readFileSafe(wxtConfigPath);
  const ratesSource = readFileSafe(ratesPath);
  const scripts = packageJson.scripts ?? {};
  const scriptEntries = Object.entries(scripts);
  const permissions = extractStringArrayByKey(wxtConfigSource, "permissions");
  const hostPermissions = extractStringArrayByKey(wxtConfigSource, "host_permissions");
  const rateProviderUrls = extractRateProviderUrls(ratesSource);

  const testFiles = [
    ...walkTestFiles(testsRoot),
    ...walkTestFiles(releaseTestsRoot),
  ];
  const testsBySuite = countTestsBySuite(testFiles);

  const knownLayout = [
    ["apps/extension", "Browser extension app (WXT + Preact)"],
    ["apps/website", "Standalone marketing website (Vite)"],
    ["docs", "Project docs and runbooks"],
    ["packages", "Shared package workspace"],
    [".github/workflows", "Automation and CI workflows"],
  ].filter(([relativePath]) => fileExists(relativePath));

  const recentCommits = getRecentCommits(8);

  const lines = [
    START_MARKER,
    "",
    "## Auto-Generated Repository Snapshot",
    "",
    "> This section is generated by `npm run readme:sync`. Do not edit manually.",
    "",
    "### Project",
    `- Package: \`${packageJson.name ?? "unknown"}\``,
    `- Description: ${packageJson.description ?? "n/a"}`,
    "",
    "### Layout",
    ...knownLayout.map(([relativePath, description]) => {
      return `- \`${relativePath}/\` - ${description}`;
    }),
    "",
    "### Extension Permissions",
    `- Core: ${
      permissions.length
        ? permissions.map((permission) => `\`${permission}\``).join(", ")
        : "none detected"
    }`,
    `- Host: ${
      hostPermissions.length
        ? hostPermissions.map((permission) => `\`${permission}\``).join(", ")
        : "none detected"
    }`,
    "",
    "### Exchange Rate Providers",
    ...(
      rateProviderUrls.length
        ? rateProviderUrls.map((url) => `- \`${url}\``)
        : ["- none detected"]
    ),
    "",
    "### Test Inventory",
    `- Total test files: \`${testFiles.length}\``,
    ...testsBySuite.map(([suite, count]) => `- ${suite}: \`${count}\``),
    "",
    "### Scripts",
    "| Script | Command |",
    "| --- | --- |",
    ...scriptEntries.map(([name, command]) => {
      return `| \`npm run ${escapeTableText(name)}\` | \`${escapeTableText(command)}\` |`;
    }),
    "",
    "### Recent Changes (first-parent, excluding README automation commits)",
    ...(
      recentCommits.length
        ? recentCommits.map((commit) => {
          return `- ${commit.date} \`${commit.hash}\` ${commit.subject}`;
        })
        : ["- No git history found in this environment."]
    ),
    "",
    END_MARKER,
  ];

  return `${lines.join("\n")}\n`;
}

function replaceAutoSection(currentReadme, nextAutoSection) {
  const normalizedCurrent = currentReadme || "";

  if (
    normalizedCurrent.includes(START_MARKER) &&
    normalizedCurrent.includes(END_MARKER)
  ) {
    const before = normalizedCurrent.split(START_MARKER)[0].replace(/\s+$/, "");
    const after = normalizedCurrent.split(END_MARKER).slice(1).join(END_MARKER).replace(/^\s+/, "");
    const withSpacingBefore = before ? `${before}\n\n` : "";
    const withSpacingAfter = after ? `\n${after}` : "";
    return `${withSpacingBefore}${nextAutoSection.trimEnd()}${withSpacingAfter}\n`;
  }

  const trimmedCurrent = normalizedCurrent.trimEnd();
  const separator = trimmedCurrent ? "\n\n" : "";
  return `${trimmedCurrent}${separator}${nextAutoSection}`;
}

function main() {
  const currentReadme = readFileSafe(readmePath);
  const nextReadme = replaceAutoSection(currentReadme, buildAutoSection());

  if (CHECK_MODE) {
    if (nextReadme !== currentReadme) {
      process.stderr.write(
        "README.md is out of sync. Run `npm run readme:sync` and commit the result.\n",
      );
      process.exit(1);
    }

    process.stdout.write("README.md is in sync.\n");
    return;
  }

  if (nextReadme === currentReadme) {
    process.stdout.write("README.md already up to date.\n");
    return;
  }

  fs.writeFileSync(readmePath, nextReadme, "utf8");
  process.stdout.write("README.md updated.\n");
}

main();
